### ISSUE TITLE
Descriptions not showing

### ISSUE THREAD

**Issue by ruhowe** [FireDragonGameStudio/FmvMaker#3]
Really like this - it's super helpful and nicely done.
Only one problem: descriptions are not showing for clickables in either the Dialog sample project or my own adapted version. Instead it is showing the name of the Clickable in the box. 
This is on Mac Big Sur with Unity 2020.2.6f1 and FmvMaker downloaded today.

**Comment by FireDragonGameStudio** [comment]
Hi @ruhowe 
first of all, sorry for my late reply. Got no notification from GitHub, so I didn't saw your issue yet. :/ I'm glad that you like FmvMaker. Although it doesn't seem like it, I'm working on new features atm. :)

The easiest solution for your problem would be to extend the ```FmvClickableFacade.cs``` with a additional serialized, referenced variable, which is a TextField or something similar and complies to your adapted version. I guess your Clickable Object Prefab is something more complex, than the default thing.

I would suggest something like this

```csharp
public class FmvClickableFacade : MonoBehaviour {

// ...

    [SerializeField]
    private Text itemText;

    // this would be the new reference
    [SerializeField]
    private Text itemDescription;

 // ...

    private void Awake() {
        // ...

        // maybe it's a good idea to replace GetComponent() with transform.Find()
        // to reference various objects of the same type
        itemDescription = transform.Find("DescriptionTextField").GetComponent<Text>();

        // ...
    }

    public void SetItemData(ClickableModel model) {
// ...
        itemDescription.text = model.Description;
        itemDescription.enabled = !string.IsNullOrEmpty(model.Description);
// ...
    }

// ...
}
```

Best regards :)

**Comment by ruhowe** [comment]
Thank you! That's really helpful.
No problem at all on the delay of course.
I've created stornaway.io for no code visual planning & previzing of FMV games & interactive video stories.
It publishes to a web player, but it can also export a json file with all the project info for integration with other systems.
I played around with scripting from my json structure to yours for a simple story and it worked.
We're working on our own Unity integrations, at the moment with some custom complex builds for specific game requirements.
But I can see a workflow where someone could draft a project in Stornaway, export a json file, translate the elements from that into your data structure, and have their project playable in Unity. Could be a great creation tool for drafting projects for delivery using FmvMaker.
Like I say, we've got plans for our own Unity export later but that won't be exclusive - our whole aim is to be a compatible authoring tool.
If you're interested, have a look at stornaway.io with the free trial - there's a 3 min getting started video on the site about it - and let me know.
Ru

**Comment by FireDragonGameStudio** [comment]
Wow, that sounds and looks really awesome! I'll have a look at it asap and would love to be kept in the loop about your progress regarding FmvMaker. :)

Best regards
Max :)

I'll close this issue for now btw. If you have further questions, please feel free to open a new issue, or reopen this one.
