### ISSUE TITLE
stop looping?

### ISSUE THREAD

**Issue by sentrywasbored** [FireDragonGameStudio/FmvMaker#4]
so I've got FMV Video for many situations in scenes. One possible outcome is inaction. However, Is there any way I can make a clickable scene A.) Not loop and B.) play other video at end?

**Comment by FireDragonGameStudio** [comment]
Hi @thesentrycoder  and sorry for the late response. Github doesn't notify me, when there is an issue posted. The solution for your problem is mentiuoned within the documentation and called an "Instant Navigation Target" -> https://github.com/FireDragonGameStudio/FmvMaker#instant-navigationtargets

**Comment by sentrywasbored** [comment]
hi, a few hours after I posted this, I said "screw it" and restarted my whole project, running individual scenes for videos and canvas button + script combo. Apologies for not mentioning this earlier and/or closing the issue
